In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3], [4, 5, 6]])

In [10]:
exp_a = np.exp(a)
exp_a

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [19]:
sum_a = np.sum(exp_a, axis=1).reshape(len(sum_a), -1)
sum_a

array([[ 30.19287485],
       [606.44010263]])

In [20]:
exp_a/sum_a

array([[0.09003057, 0.24472847, 0.66524096],
       [0.09003057, 0.24472847, 0.66524096]])

In [21]:
1/30.19287485


0.03312039694689756

In [2]:
a = pd.DataFrame({'a':[1,2,3], 'b': [2,3,4]})

In [3]:
a

a  b
0  1  2
1  2  3
2  3  4

In [4]:
b = pd.DataFrame({'a':[5,6], 'b':[7,0]})

In [5]:
b

a  b
0  5  7
1  6  0

In [8]:
pd.concat([a, b], axis=0)

a  b
0  1  2
1  2  3
2  3  4
0  5  7
1  6  0